package twitter4jads.models.ads.cards;

public enum CardType {

    IMAGE_APP,
    IMAGE_CAROUSEL_APP,
    IMAGE_CAROUSEL_WEBSITE,
    IMAGE_MULTI_DEST_CAROUSEL_APP,
    IMAGE_MULTI_DEST_CAROUSEL_WEBSITE,
    IMAGE_WEBSITE,
    MIXED_MEDIA_MULTI_DEST_CAROUSEL_APP,
    MIXED_MEDIA_MULTI_DEST_CAROUSEL_WEBSITE,
    MIXED_MEDIA_SINGLE_DEST_CAROUSEL_APP,
    MIXED_MEDIA_SINGLE_DEST_CAROUSEL_WEBSITE,
    VIDEO_APP,
    VIDEO_CAROUSEL_APP,
    VIDEO_CAROUSEL_WEBSITE,
    VIDEO_MULTI_DEST_CAROUSEL_APP,
    VIDEO_MULTI_DEST_CAROUSEL_WEBSITE,
    VIDEO_WEBSITE

}
